# Generated by Django 4.1.3 on 2022-11-14 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fortesting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dummymodel",
            name="rating",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
